name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for cross-platform builds, if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub using GitHub secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push the Docker image
      - name: Build and push Docker image
        id: docker_build  # Add an ID to the step to reference its outputs
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: darshu12/Python_actions:latest
          outputs:  # Ensure the output is set here
            # You might want to set the actual output options depending on your use case
            digest: true  # Assuming you want the digest output

      # Step 5 (Optional): Output the Docker image digest (to confirm the build)
      - name: Image digest
        run: echo "Docker image digest: ${{ steps.docker_build.outputs.digest }}"
